name: unit test + build

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.5"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      
    - name: Make and run unit test
      run: make test DEBUG=1 && ./libft/utest && ./utest && make fclean && make